# 这些是通过 .github/FUNDING.yml 支持本项目的方式
# 详情: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [your-github-username]
# patreon: # 用 Patreon 替换 username
# open_collective: # 用 Open Collective 替换 username
# ko_fi: # 用 Ko-fi 替换 username
# tidelift: # 用 Tidelift 替换 package-name
# community_bridge: # 用 Community Bridge 替换 project-name
# liberapay: # 用 Liberapay 替换 username
# issuehunt: # 用 IssueHunt 替换 username
# otechie: # 用 Otechie 替换 username
# lfx_crowdfunding: # 用 LFX Crowdfunding 替换 username
# custom: # 最多 4 个 sponsor URLs
